server:
  port: 8761
logging:
  level:
    root: INFO
security:
  user:
    name: user
    password: password
eureka:
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
    register-with-eureka: false
    fetch-registry: false
    