server:
  port: 7901
logging:
  level:
    root: INFO
spring:
  application:
    name: eureka-movie
eureka: 
  client:
    service-url:
      defaultZone: http://user:password@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}